apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: loginwebapp-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: loginwebapp-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: loginwebapp-clusterrole
  apiGroup: rbac.authorization.k8s.io
