apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: loginwebapp-clusterrole
rules:
- apiGroups: [""]
  resources: ["nodes", "persistentvolumes"]
  verbs: ["get", "list", "watch"]
