apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: loginwebapp-rolebinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: loginwebapp-sa
  namespace: default
roleRef:
  kind: Role
  name: loginwebapp-role
  apiGroup: rbac.authorization.k8s.io
