---
- name: Deploy 3-Tier Application to Kubernetes
  hosts: localhost
  tasks:

    - name: Apply Apache ServiceAccount
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', 'apache-sa.yml') }}"

    - name: Apply WebLogic ServiceAccount
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', 'weblogic-sa.yml') }}"

    - name: Apply MySQL ServiceAccount
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', 'mysql-sa.yml') }}"

    - name: Apply Apache Role
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', 'apache-role.yml') }}"

    - name: Apply WebLogic Role
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', 'weblogic-role.yml') }}"

    - name: Apply MySQL Role
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', 'mysql-role.yml') }}"

    - name: Apply Apache RoleBinding
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', 'apache-rolebinding.yml') }}"

    - name: Apply WebLogic RoleBinding
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', 'weblogic-rolebinding.yml') }}"

    - name: Apply MySQL RoleBinding
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', 'mysql-rolebinding.yml') }}"

    - name: Apply Apache ClusterRoleBinding
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', 'apache-clusterrolebinding.yml') }}"

    - name: Apply WebLogic ClusterRoleBinding
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', 'weblogic-clusterrolebinding.yml') }}"

    - name: Apply MySQL ClusterRoleBinding
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', 'mysql-clusterrolebinding.yml') }}"

    - name: Apply Apache Deployment
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', 'apache-deployment.yml') }}"

    - name: Apply WebLogic Deployment
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', 'weblogic-deployment.yml') }}"

    - name: Apply MySQL Deployment
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', 'mysql-deployment.yml') }}"

    - name: Apply Apache Service
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', 'apache-service.yml') }}"

    - name: Apply WebLogic Service
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', 'weblogic-service.yml') }}"

    - name: Apply MySQL Service
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', 'mysql-service.yml') }}"
