---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: weblogic-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: weblogic-role
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps"]
    verbs: ["get", "list", "watch", "create", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: weblogic-rolebinding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: weblogic-sa
    namespace: default
roleRef:
  kind: Role
  name: weblogic-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: weblogic-clusterrole
rules:
  - apiGroups: [""]
    resources: ["nodes", "pods", "services", "events"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: weblogic-clusterrolebinding
subjects:
  - kind: ServiceAccount
    name: weblogic-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: weblogic-clusterrole
  apiGroup: rbac.authorization.k8s.io
